ALTER TABLE profiles ADD COLUMN IF NOT EXISTS injuries TEXT DEFAULT '';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS job_type TEXT DEFAULT 'mixed';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gender TEXT DEFAULT 'male';
